# Generated by Django 5.2.1 on 2025-05-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0004_alter_qr_imagen_qr_registrovehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='Marca del vehiculo'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='modelo',
            field=models.CharField(max_length=50, verbose_name='Modelo del vehiculo'),
        ),
    ]
